spring.application.name=youx
spring.datasource.url=jdbc:postgresql://localhost:5432/clinica
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.locations=classpath:db/migration
spring.flyway.enabled=true
spring.flyway.schemas=public
api.security.token.secret={JWT_SECRET:mu-secret-key}
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
spring.jackson.serialization.INDENT_OUTPUT=true
